jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v3
      with:
        close-issue-message: 'This issue has been automatically closed due to inactivity.

          '
        days-before-close: 14
        days-before-stale: 180
        exempt-all-milestones: true
        exempt-issue-labels: automation,backlog,builds,codetree-epic,developer,documentation,high,in
          progress,security,test,triage,tech debt
        stale-issue-label: stale
        stale-issue-message: 'This issue has been automatically marked as stale because
          it has not had recent activity. It will be closed if no further activity
          occurs, per  https://github.com/rstudio/rstudio/wiki/Issue-Grooming. Thank
          you for your contributions.

          '
name: Close stale issues
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  contents: read
